### ISSUE TITLE
 fusion reactor mk2

### ISSUE THREAD

**Issue by LazyTurtle61** [jimmyjon711/FactorioExtended-Equipment#14]
i wanted to make a portable fusion reactor but i have space exploration installed, and it replaces the normal fusion reactors to a diffrent version but for the mk2 fusion reactor i need to have the vanilla ones but they are removed because of space exploration, maybe make another recipe where u can use the fusion reactor from space exploration because i cant make the mk2 from your mod right now.

**Comment by billbo99** [comment]
Mk1 fusion reactors still exist in the in the research tree,  just that Space Exploration has moved them behind "Deep Space Science".  Which as I understand it is very late game research.

Thruster suits mk3 has nearly the same size grid,  mk4 has a bigger grid.
