### ISSUE TITLE
Power armour mk3 Not showing any armour

### ISSUE THREAD

**Issue by LazyTurtle61** [jimmyjon711/FactorioExtended-Equipment#15]
![Aantekening 2020-05-30 142529](https://user-images.githubusercontent.com/64089224/83328181-665be200-a281-11ea-867d-b45a32ea9627.png)

**Comment by LazyTurtle61** [comment]
are u active???

**Comment by jimmyjon711** [comment]
I am not as active anymore.
What other mods do you have installed?
Have you just tried this mod pack without other mods and does it show up?

**Comment by LazyTurtle61** [comment]
I use space exploration with all of factorio extended plus

**Comment by jimmyjon711** [comment]
I do see that there is a problem with just this mod, currently looking into it

**Comment by LazyTurtle61** [comment]
Thnx

**Comment by jimmyjon711** [comment]
It has been uploaded to the mod portal
