### ISSUE TITLE
power-armor-2

### ISSUE THREAD

**Issue by rotten-84** [jimmyjon711/FactorioExtended-Equipment#3]
error in asssignID technology with name power-armor-2 does not exist

**Comment by pditterline** [comment]
Submitted a PR #4 with a fix for this, though I think it might not correctly transfer research from power-armor-3 to power-armor-mk3. It fixes the power-armor-2 errors and allows the mod to load.

**Comment by jimmyjon711** [comment]
Fixed with merge from @pditterline dd2f1954fb726fa03675dddbd4dfca47cfb1fc5b
