### ISSUE TITLE
Error when loaded with Endgame Combat

### ISSUE THREAD

**Issue by LuziferSenpai** [jimmyjon711/FactorioExtended-Equipment#6]
<img width="1092" alt="factorio_883ujb4Qee" src="https://user-images.githubusercontent.com/38015859/60502521-49f4a580-9cbe-11e9-8617-ddf72f5c8fa3.png">

**Comment by jimmyjon711** [comment]
Thanks for the report, I am currently on vacation right now and will look into it when I get back.

**Comment by LuziferSenpai** [comment]
Reika(Endgame Dev), has already fixed it in her MOD, with having your Modification as "?" Denpency.
