### ISSUE TITLE
error on loading mod

### ISSUE THREAD

**Issue by eyekoms** [jimmyjon711/FactorioExtended-Equipment#8]
Hi,

I downloaded your mods and I wanted to start a new game, but there is an error with the name of personal laser defense - see attached image. It occurs also if I only load this mod without any other.

Thank you very much in advance for fixing it.

Best regards

![error](https://user-images.githubusercontent.com/31281010/72268983-1b6b6600-3623-11ea-92db-e1196324ff73.png)

**Comment by eyekoms** [comment]
Hello again,

after installing the Weaponry-mod the error no longer occurs.

Greetings

**Comment by ByPaco10** [comment]
Same problem here, in the factorio mod portal and in the game itself there isen't nothing warning you about the Weaponry-mod needed. I will try that solution

**Comment by ByPaco10** [comment]
Yeah, thats the problem, Plus-Weaponry should be added like a dependency, you can close this issue

**Comment by jimmyjon711** [comment]
Fixed by with 14f708e9cd3264ce3317ddce835bc7a67599b0b3 commit
